Error out from the build process if any replace or patch fails to apply

diff --git a/src/php-wasm/wasm/Dockerfile b/src/php-wasm/wasm/Dockerfile
--- a/src/php-wasm/wasm/Dockerfile
+++ b/src/php-wasm/wasm/Dockerfile
@@ -50,6 +50,8 @@ for dir in $(ls $1); do \n\
     cp -r /root/$1/$dir/* /root/lib/$dir/ 2>/dev/null || :; \n\
     done ' > /root/copy-lib.sh
 RUN chmod a+x /root/copy-lib.sh
+# Script to replace strings in files and exit with a non-zero status if the string is not found.
+COPY ./build-assets/replace.pl /root/replace.pl
 
 # Patch emcc to allow skipping flags and passing additional flags using environment variables.
 # 
@@ -89,7 +91,8 @@ COPY ./build-assets/zlib /root/zlib
 RUN source /root/emsdk/emsdk_env.sh && \
     cd /root/zlib && \
     emconfigure ./configure --prefix=/root/lib && \
-    # emmake make fails after it built the library files – let's ignore the errors \
+    # emmake make fails, but only after it builds the library files. 
+    # Let's just ignore the errors and proceed with the built libraries.
     (EMCC_FLAGS="-fPIC" emmake make || true) && \
     EMCC_FLAGS="-fPIC" emmake make install
 
@@ -138,28 +141,22 @@ RUN     set -euxo pipefail &&\
         cd ncurses  && \
         cp make_hash make_hash_x86  && \
         cp make_keys make_keys_x86  && \
-        cp report_offsets report_offsets_x86  && \
+        cp report_offsets report_offsets_x86   && \
         cd /root/ncurses-6.2 && \
         make clean && \
-        git apply --no-index /root/ncurses.patch && \
-        perl -pi.bak -e 's/\.\/make_hash/.\/make_hash_x86/g' ncurses/tinfo/MKcaptab.sh && \
-        perl -pi.bak -e 's/\.\/make_hash/.\/make_hash_x86/g' ncurses/tinfo/MKuserdefs.sh && \
-        perl -pi.bak -e 's/make_hash\$\(BUILD_EXEEXT/make_hash_x86\$(BUILD_EXEEXT/g' ncurses/Makefile.in && \
-        perl -pi.bak -e 's/make_keys\$\(BUILD_EXEEXT/make_keys_x86\$(BUILD_EXEEXT/g' ncurses/Makefile.in && \
-        perl -pi.bak -e 's/\.\/report_offsets\$\(BUILD_EXEEXT/.\/report_offsets_x86\$(BUILD_EXEEXT/g' ncurses/Makefile.in && \
+        git apply --ignore-space-change --ignore-whitespace --no-index /root/ncurses.patch && \
         source /root/emsdk/emsdk_env.sh && \
         emconfigure ./configure \
             PKG_CONFIG_PATH=$PKG_CONFIG_PATH \
             --build i386-pc-linux-gnu \
             --prefix=/root/lib && \
-        perl -pi.bak -e 's/^\s+cd man.*$//g' Makefile && \
-        perl -pi.bak -e 's/^\s+cd progs.*$//g' Makefile && \
-        perl -pi.bak -e 's/^\s+cd test.*$//g' Makefile && \
-        perl -pi.bak -e 's/^\s+cd misc.*$//g' Makefile && \
-        perl -pi.bak -e 's/^\s+cd c\+\+.*$//g' Makefile && \
+        perl /root/replace.pl '^\s+cd man.*$' '' Makefile && \
+        perl /root/replace.pl '^\s+cd progs.*$' '' Makefile && \
+        perl /root/replace.pl '^\s+cd test.*$' '' Makefile && \
+        perl /root/replace.pl '^\s+cd misc.*$' '' Makefile && \
+        perl /root/replace.pl '^\s+cd c\+\+.*$' '' Makefile && \
         emmake make && \
         emmake make install
-
 
 # Compile libedit (readline alternative)
 FROM emscripten AS emscripten-libedit
@@ -314,7 +311,7 @@ RUN if [ "$WITH_LIBZIP" = "yes" ]; then \
         /root/copy-lib.sh lib-libz; \
         /root/copy-lib.sh lib-libzip && \
         if [ "${PHP_VERSION:0:1}" -le "5" ]; then \
-            perl -pi.bak -e 's/ZEND_MODULE_GLOBALS_CTOR_N/(void (*)(void *))ZEND_MODULE_GLOBALS_CTOR_N/g' /root/php-src/ext/zlib/zlib.c; \
+            perl /root/replace.pl ZEND_MODULE_GLOBALS_CTOR_N '(void (*)(void *))ZEND_MODULE_GLOBALS_CTOR_N' /root/php-src/ext/zlib/zlib.c; \
         fi;\
         if [[ "${PHP_VERSION:0:1}" -le "7" && "${PHP_VERSION:2:1}" -le "3" ]] || [ "${PHP_VERSION:0:1}" -le "5" ]; then \
             apt install -y zlib1g zlib1g-dev; \
@@ -332,8 +329,8 @@ RUN if [ "$WITH_LIBZIP" = "yes" ]; then \
             echo -n ' -I /root/zlib -I /root/libzip' >> /root/.emcc-php-wasm-flags; \
             echo -n ' /root/lib/lib/libzip.a /root/lib/lib/libz.a' >> /root/.emcc-php-wasm-sources; \
         fi && \
-        perl -pi.bak -e 's/pharcmd=pharcmd/pharcmd=/g' /root/php-src/configure && \
-        perl -pi.bak -e 's/pharcmd_install=install-pharcmd/pharcmd_install=/g' /root/php-src/configure; \
+        perl /root/replace.pl pharcmd=pharcmd pharcmd= /root/php-src/configure && \
+        perl /root/replace.pl pharcmd_install=install-pharcmd pharcmd_install= /root/php-src/configure; \
     fi;
 
 # Add ncurses if needed and libedit if needed
@@ -349,9 +346,9 @@ RUN if [ "$WITH_CLI_SAPI" = "yes" ]; \
         echo -n ', "_run_cli", "_wasm_add_cli_arg"' >> /root/.EXPORTED_FUNCTIONS && \
         echo -n ' -DWITH_CLI_SAPI=1 -lncurses -ledit ' >> /root/.emcc-php-wasm-flags; \
         # Disable dlopen() in the readline PHP extension
-        perl -pi.bak -e 's/define HAVE_DLOPEN 1/define HAVE_DLOPEN 0/g' /root/php-src/main/php_config.h; \
+        perl /root/replace.pl '/define HAVE_DLOPEN 1' 'define HAVE_DLOPEN 0' /root/php-src/main/php_config.h; \
         echo '#undef COMPILE_DL_READLINE' >> /root/php-src/main/php_config.h; \
-        perl -pi.bak -e 's/GET_SHELL_CB\(cb\);/(cb) = php_cli_get_shell_callbacks();/g' /root/php-src/ext/readline/readline_cli.c; \
+        perl /root/replace.pl '/GET_SHELL_CB\(cb\);' '(cb) = php_cli_get_shell_callbacks();' /root/php-src/ext/readline/readline_cli.c; \
     else \
         echo -n ' --disable-cli ' >> /root/.php-configure-flags; \
     fi;
@@ -367,10 +364,10 @@ RUN if [ "$WITH_LIBXML" = "yes" ]; \
         # Libxml check is wrong in PHP < 7.4.0.
         # In the regular cc it's just a warning,
         # but in the emscripten's emcc that's an error:
-        perl -pi.bak -e "s/char xmlInitParser/void xmlInitParser/g" /root/php-src/configure; \
+        perl /root/replace.pl "char xmlInitParser' 'void xmlInitParser" /root/php-src/configure; \
         # On PHP < 7.1.0, the dom_iterators.c file implicitly converts *char to const *char causing emcc error
         if [[ "${PHP_VERSION:0:1}" -le "7" && "${PHP_VERSION:2:1}" -le "0" ]] || [ "${PHP_VERSION:0:1}" -le "5" ]; then \
-            perl -pi.bak -e 's/xmlHashScan\(ht, itemHashScanner, iter\);/xmlHashScan(ht, (xmlHashScanner)itemHashScanner, iter);/g' /root/php-src/ext/dom/dom_iterators.c; \
+            perl /root/replace.pl 'xmlHashScan\(ht, itemHashScanner, iter\);' 'xmlHashScan(ht, (xmlHashScanner)itemHashScanner, iter);' /root/php-src/ext/dom/dom_iterators.c; \
         fi; \
     else \
         echo -n ' --disable-libxml --without-libxml --disable-dom --disable-xml --disable-simplexml --disable-xmlwriter' >> /root/.php-configure-flags; \
@@ -488,7 +485,7 @@ RUN source /root/emsdk/emsdk_env.sh && \
 RUN echo '#define ZEND_MM_ERROR 0' >> /root/php-src/main/php_config.h; 
 
 # With HAVE_UNISTD_H=1 PHP complains about the missing getdtablesize() function 
-RUN perl -pi.bak -e 's/define HAVE_UNISTD_H 1/define HAVE_UNISTD_H 0/g' /root/php-src/main/php_config.h
+RUN perl /root/replace.pl 'define HAVE_UNISTD_H 1' 'define HAVE_UNISTD_H 0' /root/php-src/main/php_config.h
 
 # PHP <= 7.3 is not very good at detecting the presence of the POSIX readdir_r function
 # so we need to force it to be enabled.
@@ -497,7 +494,7 @@ RUN if [[ "${PHP_VERSION:0:1}" -le "7" && "${PHP_VERSION:2:1}" -le "3" ]] || [ "
     fi;
 
 # Rename the original php_pollfd_for() implementation so that we can link our own version.
-RUN perl -pi.bak -e 's/static inline int php_pollfd_for\(/int php_pollfd_for(php_socket_t fd, int events, struct timeval *timeouttv); static inline int __real_php_pollfd_for\(/g' /root/php-src/main/php_network.h
+RUN perl /root/replace.pl 'static inline int php_pollfd_for\(' 'int php_pollfd_for(php_socket_t fd, int events, struct timeval *timeouttv); static inline int __real_php_pollfd_for\(' /root/php-src/main/php_network.h
 
 RUN source /root/emsdk/emsdk_env.sh && \
     # We're compiling PHP as emscripten's side module...
@@ -873,22 +870,22 @@ RUN \
             export WASM_URL="$WASM_FILENAME"; \
         fi; \
     # Make the php.wasm URL configurable via the dependencyFilename loader argument:
-        perl -pi.bak -e 's#"php\.wasm"#dependencyFilename#g' /root/output/php.js && \
-        perl -pi.bak -e "s#'php\.wasm'#dependencyFilename#g" /root/output/php.js && \
+        perl /root/replace.pl '"php\.wasm"' dependencyFilename /root/output/php.js && \
+        perl /root/replace.pl "'php\.wasm'" dependencyFilename /root/output/php.js && \
     # Patch a "property undefined" error
         # Emscripten produces an if that checkes a stream.stream_ops.poll property. However,
         # stream.stream_ops is sometimes undefined and the check fails. Let's adjust it to
         # tolerate a null stream.stream_ops value.
-        perl -pi.bak -e "s#if\s*\(stream\.stream_ops\.poll\)#if (stream.stream_ops?.poll)#g" /root/output/php.js && \
+        perl /root/replace.pl "if\s*\(stream\.stream_ops\.poll\)" "if (stream.stream_ops?.poll)" /root/output/php.js && \
     # Make Emscripten websockets configurable
         # Emscripten makes the Websocket proxy connect to a fixed URL.
         # This assumes the traffic is always forwarded to the same target.
         # However, we want to support arbitrary targets, so we need to
         # replace the hardcoded websocket target URL with a dynamic callback.
-        perl -pi.bak -e $'s#if\s*\(\s*["\']string["\']\s*===\s*typeof Module\[["\']websocket["\']\]\[["\']url["\']\]\s*\)#if("function"===typeof Module["websocket"]["url"]) {\nurl = Module["websocket"]["url"](...arguments);\n}else if ("string" === typeof Module["websocket"]["url"])#g' \
+        perl /root/replace.pl $'if\s*\(\s*["\']string["\']\s*===\s*typeof Module\[["\']websocket["\']\]\[["\']url["\']\]\s*\)' $'if("function"===typeof Module["websocket"]["url"]) {\nurl = Module["websocket"]["url"](...arguments);\n}else if ("string" === typeof Module["websocket"]["url"])' \
             /root/output/php.js && \
         # Enable custom WebSocket constructors to support socket options.
-        perl -pi.bak -e "s#ws = new WebSocketConstructor#if (Module['websocket']['decorator']) {WebSocketConstructor = Module['websocket']['decorator'](WebSocketConstructor);}ws = new WebSocketConstructor#g" /root/output/php.js && \
+        perl /root/replace.pl "ws = new WebSocketConstructor" "if (Module['websocket']['decorator']) {WebSocketConstructor = Module['websocket']['decorator'](WebSocketConstructor);}ws = new WebSocketConstructor" /root/output/php.js && \
     # Add MSG_PEEK flag support in recvfrom
         #
         # Emscripten ignores the flags argument to ___syscall_recvfrom.
@@ -900,9 +897,9 @@ RUN \
         # reading the remaining "TTP/1.1 200 OK" and not recognizing it as a valid
         # status line.
         # We need to patch the syscall to support the MSG_PEEK flag.
-        perl -pi.bak -e 's#sock\.sock_ops\.recvmsg\(sock,\s*len\);#sock.sock_ops.recvmsg(sock, len, typeof flags !== "undefined" ? flags : 0);#g' /root/output/php.js && \
-        perl -pi.bak -e 's#recvmsg:\s*function\(sock,\s*length\)#recvmsg: function(sock, length, flags)#g' /root/output/php.js && \
-        perl -pi.bak -e 's#if\s*\(sock\.type\s*===\s*1\s*&&\s*bytesRead\s*<\s*queuedLength\)#if (flags&2) {bytesRead = 0;} if (sock.type === 1 && bytesRead < queuedLength)#g' /root/output/php.js && \
+        perl /root/replace.pl 'sock\.sock_ops\.recvmsg\(sock,\s*len\);' 'sock.sock_ops.recvmsg(sock, len, typeof flags !== "undefined" ? flags : 0);' /root/output/php.js && \
+        perl /root/replace.pl 'recvmsg:\s*function\(sock,\s*length\)' 'recvmsg: function(sock, length, flags)' /root/output/php.js && \
+        perl /root/replace.pl 'if\s*\(sock\.type\s*===\s*1\s*&&\s*bytesRead\s*<\s*queuedLength\)' 'if (flags&2) {bytesRead = 0;} if (sock.type === 1 && bytesRead < queuedLength)' /root/output/php.js && \
     # Replace the hardcoded ENVIRONMENT variable with a dynamic computation
         #
         # The JavaScript code of the web loader and web worker loader is identical,
@@ -914,8 +911,8 @@ RUN \
         # separate copies of the code. Instead, we use a dynamic computation of the
         # environment, based on the `RuntimeName` variable, which is an argument to the
         # wrapper function.
-        perl -pi.bak -e 's/ENVIRONMENT_IS_([A-Z]+)\s*=\s*(true|false)/ENVIRONMENT_IS_\1=RuntimeName==="\1"/g' /root/output/php.js && \
-        perl -pi.bak -e 's/var ENV\s*=\s*\{\}/var ENV = PHPLoader.ENV || {}/g' /root/output/php.js && \
+        perl /root/replace.pl 'ENVIRONMENT_IS_([A-Z]+)\s*=\s*(true|false)' 'ENVIRONMENT_IS_\1=RuntimeName==="\1"' /root/output/php.js && \
+        perl /root/replace.pl 'var ENV\s*=\s*\{\}' 'var ENV = PHPLoader.ENV || {}' /root/output/php.js && \
     # Turn the php.js file into an ES module
         # Manually turn the output into a esm module instead of relying on -s MODULARIZE=1.
         # which pollutes the global namespace and does not play well with import() mechanics.
