Libzip support for php 5.6

diff --git a/src/php-wasm/wasm/Dockerfile b/src/php-wasm/wasm/Dockerfile
--- a/src/php-wasm/wasm/Dockerfile
+++ b/src/php-wasm/wasm/Dockerfile
@@ -62,7 +62,7 @@ RUN set -euxo pipefail;\
 # PHP <= 7.3 requires Bison 2.7
 # PHP >= 7.4 and Bison 3.0
 COPY ./build-assets/bison27.patch /root/bison27.patch
-RUN if [ "${PHP_VERSION:0:1}" -le "7" ] && [ "${PHP_VERSION:2:1}" -le "3" ]; then \
+RUN if [[ "${PHP_VERSION:0:1}" -le "7" && "${PHP_VERSION:2:1}" -le "3" ]] || [ "${PHP_VERSION:0:1}" -le "5" ]; then \
         wget http://ftp.gnu.org/gnu/bison/bison-2.7.tar.gz && \
         tar -xvf bison-2.7.tar.gz && \
         rm bison-2.7.tar.gz && \
@@ -115,31 +115,47 @@ RUN if [ "$WITH_LIBXML" = "yes" ]; \
 COPY ./build-assets/zlib /root/zlib
 RUN if [ "$WITH_LIBZIP" = "yes" ]; then \
         source /root/emsdk/emsdk_env.sh && \
-        cd /root/zlib && \
-        emconfigure ./configure --prefix=/root/lib && \
-        # emmake make fails after it built the library files – let's ignore the errors \
-        (emmake make || true) && \
-        emmake make install && \
-        cd /root && \
-        curl -k https://libzip.org/download/libzip-1.9.2.tar.gz -o libzip-1.9.2.tar.gz && \
-        tar -xzf libzip-1.9.2.tar.gz && \
-        mv libzip-1.9.2 libzip && \
-        cd libzip && \
-        mkdir build && \
-        cd build && \
-        emcmake cmake \
-            -DCMAKE_INSTALL_PREFIX=/root/lib \
-            -DZLIB_LIBRARY=/root/lib/lib/libz.a \
-            -DZLIB_INCLUDE_DIR=/root/lib/include \
-            .. && \
-        emmake make && \
-        emmake make install; \
-    fi
-
-RUN if [ "$WITH_LIBZIP" = "yes" ]; then \
-        echo -n ' --with-zip' >> /root/.php-configure-flags; \
-        echo -n ' -I /root/zlib -I /root/libzip' >> /root/.emcc-php-wasm-flags; \
-        echo -n ' /root/lib/lib/libzip.a /root/lib/lib/libz.a' >> /root/.emcc-php-wasm-sources; \
+        if [ "${PHP_VERSION:0:1}" -ge "7" ]; then \
+            cd /root/zlib && \
+            emconfigure ./configure --prefix=/root/lib && \
+            # emmake make fails after it built the library files – let's ignore the errors \
+            (emmake make || true) && \
+            emmake make install && \
+            cd /root && \
+            curl -k https://libzip.org/download/libzip-1.9.2.tar.gz -o libzip-1.9.2.tar.gz && \
+            tar -xzf libzip-1.9.2.tar.gz && \
+            mv libzip-1.9.2 libzip && \
+            cd libzip && \
+            mkdir build && \
+            cd build && \
+            emcmake cmake \
+                -DCMAKE_INSTALL_PREFIX=/root/lib \
+                -DZLIB_LIBRARY=/root/lib/lib/libz.a \
+                -DZLIB_INCLUDE_DIR=/root/lib/include \
+                .. && \
+            emmake make && \
+            emmake make install; \
+        else\
+            cd /root/zlib && \
+            emconfigure ./configure --prefix=/root/lib && \
+            # emmake make fails after it built the library files – let's ignore the errors \
+            (emmake make || true) && \
+            emmake make install && \
+            cd /root && \
+            curl -k https://libzip.org/download/libzip-1.2.0.tar.gz -o libzip-1.2.0.tar.gz && \
+            tar -xzf libzip-1.2.0.tar.gz && \
+            mv libzip-1.2.0 libzip && \
+            cd libzip && \
+            mkdir build && \
+            cd build && \
+            emcmake cmake \
+                -DCMAKE_INSTALL_PREFIX=/root/lib \
+                -DZLIB_LIBRARY=/root/lib/lib/libz.a \
+                -DZLIB_INCLUDE_DIR=/root/lib/include \
+                .. && \
+            emmake make && \
+            emmake make install; \
+        fi\
     fi
 
 # Get and patch PHP
@@ -176,8 +192,22 @@ RUN if [ "$WITH_VRZNO" = "yes" ]; \
         echo -n ', "_exec_callback", "_del_callback"' >> /root/.EXTRA_EXPORTED_FUNCTIONS; \
     fi
 
+RUN if [ "$WITH_LIBZIP" = "yes" ]; then \
+        if [ "${PHP_VERSION:0:1}" -eq "5" ]; then \
+            echo -n ' --enable-zip --with-libzip=/root/lib ' >> /root/.php-configure-flags; \
+            cp /root/lib/lib/libzip/include/zipconf.h /root/lib/lib; \
+            #echo -n ' -I /root/zlib -I /root/libzip ' >> /root/.emcc-php-wasm-flags; \
+            #echo -n ' /root/lib/lib/libzip.a /root/lib/lib/libz.a' >> /root/.emcc-php-wasm-sources; \
+        else \
+            echo -n ' --with-zip' >> /root/.php-configure-flags; \
+            echo -n ' -I /root/zlib -I /root/libzip' >> /root/.emcc-php-wasm-flags; \
+            echo -n ' /root/lib/lib/libzip.a /root/lib/lib/libz.a' >> /root/.emcc-php-wasm-sources; \
+        fi; \
+    fi
+
 # Build the patched PHP
 RUN cd php-src/ && PKG_CONFIG_PATH=$PKG_CONFIG_PATH ./buildconf --force
+RUN apt install -y zlib1g zlib1g-dev
 RUN source /root/emsdk/emsdk_env.sh && \
     cd php-src/ && \
     emconfigure ./configure \
@@ -219,10 +249,17 @@ RUN source /root/emsdk/emsdk_env.sh && \
 
 # PHP <= 7.3 is not very good at detecting the presence of the POSIX readdir_r function
 # so we need to force it to be enabled.
-RUN if [ "${PHP_VERSION:0:1}" -le "7" ] && [ "${PHP_VERSION:2:1}" -le "3" ]; then \
+RUN if [[ "${PHP_VERSION:0:1}" -le "7" && "${PHP_VERSION:2:1}" -le "3" ]] || [ "${PHP_VERSION:0:1}" -le "5" ]; then \
         echo '#define HAVE_POSIX_READDIR_R 1' >> php-src/main/php_config.h; \
     fi;
 
+# RUN cp /root/lib/lib/libzip/include/zipconf.h /root/lib/lib/include
+RUN cp /root/lib/lib/libzip/include/zipconf.h /root/lib/include; \
+    echo '#define LIBZIP_VERSION "1.2.0"' >> /root/lib/include/zipconf.h; \
+    cp /root/lib/include/*.h /root/php-src;
+
+RUN ls /root/php-src
+#RUN cp /root/lib/lib/libzip/include/zipconf.h /root/php-src/main;
 RUN source /root/emsdk/emsdk_env.sh && \
     cd php-src/ && \
     emmake make -j8
@@ -248,6 +285,8 @@ RUN if [ "${PHP_VERSION:0:1}" -lt "8" ]; then \
     echo -n ' -s EMULATE_FUNCTION_POINTER_CASTS=1' >> /root/.emcc-php-wasm-flags; \
     fi
 
+RUN echo -n ' -I /root/zlib -I /root/libzip ' >> /root/.emcc-php-wasm-flags; \
+    echo -n ' /root/lib/lib/libzip.a /root/lib/lib/libz.a' >> /root/.emcc-php-wasm-sources;
 # Build the final .wasm file
 RUN mkdir /root/output
 RUN source /root/emsdk/emsdk_env.sh && \
